---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: vagrant
  vars:
    nr_hugepages: 2048
    uname_r: 4.2.0-35-generic
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    netsniff_dir: "{{ install_dir }}/netsniff-ng"
    dpdk_dir: "{{ install_dir }}/dpdk"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - common

- name: install pktgen
  hosts: pktgen 
  remote_user: vagrant
  vars:
    install_dir: "{{ ansible_env.HOME }}/dpdk-home"
    dpdk_dir: "{{ install_dir }}/dpdk"
    pktgen_dir: "{{ install_dir }}/pktgen-dpdk"
    dpdk_target: x86_64-ivshmem-linuxapp-gcc
  roles:
    - pktgen
