---
# Deploys the whole application stack in this site.

- name: apply all base packages
  hosts: all
  remote_user: vagrant
  vars:
    netsniff_dir: "{{ ansible_env.HOME }}/netsniff-ng"
  roles:
    - common

- name: install dpdk
  hosts: dpdk1
  remote_user: vagrant
  vars:
    nr_hugepages: 1024
    uname_r: 4.2.0-35-generic
    dpdk_dir: "{{ ansible_env.HOME }}/dpdk"
  roles:
    - dpdk1

- name: install pktgen
  hosts: pktgen 
  remote_user: vagrant
  vars:
    nr_hugepages: 1024
    uname_r: 4.2.0-35-generic
    dpdk_dir: "{{ ansible_env.HOME }}/dpdk"
    pktgen_dir: "{{ ansible_env.HOME }}/pktgen-dpdk"
  roles:
    - pktgen
