---
- hosts: all
  sudo: true
  user: vagrant
  tasks:
    - apt: pkg=git update_cache=yes state=latest
    - apt: pkg=vim update_cache=no state=latest
    - apt: pkg=emacs update_cache=no state=latest
    - apt: pkg=ruby update_cache=no state=latest
    - apt: pkg=curl update_cache=no state=latest
    - apt: pkg=wget update_cache=no state=latest
    - apt: pkg=tmux update_cache=no state=latest

- hosts: all
  user: vagrant
  tasks:
    - copy: src=config/tmux.conf dest={{ ansible_env.HOME }}/.tmux.conf
