---

- hosts: all
  sudo: true
  user: vagrant
  tasks:
    # Install packages for netsniff-ng
    - apt: pkg=pkg-config update_cache=no state=latest
    - apt: pkg=flex update_cache=no state=latest
    - apt: pkg=bison update_cache=no state=latest
    - apt: pkg=libnacl-dev update_cache=no state=latest
    - apt: pkg=libnl-cli-3-dev update_cache=no state=latest
    - apt: pkg=libnetfilter-conntrack-dev update_cache=no state=latest
    - apt: pkg=liburcu-dev update_cache=no state=latest
    - apt: pkg=libncurses5-dev update_cache=no state=latest
    - apt: pkg=libgeoip-dev update_cache=no state=latest
    - apt: pkg=libpcap-dev update_cache=no state=latest
    - apt: pkg=libcli-dev update_cache=no state=latest
    - apt: pkg=libnet1-dev update_cache=no state=latest

- hosts: all
  user: vagrant
  tasks:
    - git: repo=https://github.com/netsniff-ng/netsniff-ng.git
           dest={{ ansible_env.HOME }}/tmp
    - command: bash configure chdir={{ ansible_env.HOME }}/tmp
    - command: make chdir={{ ansible_env.HOME }}/tmp
    - command: sudo make install chdir={{ ansible_env.HOME }}/tmp

