---
- hosts: all
  user: vagrant
  tasks:
    - git: repo=https://github.com/rbenv/rbenv.git
           dest={{ ansible_env.HOME }}/.rbenv
    - command: src/configure chdir={{ ansible_env.HOME }}/.rbenv
    - command: make -C src chdir={{ ansible_env.HOME }}/.rbenv
    - copy: src=config/bash_profile dest={{ ansible_env.HOME }}/.bash_profile

    - git: repo=https://github.com/rbenv/ruby-build.git
           dest={{ ansible_env.HOME }}/.rbenv/plugins/ruby-build
