---
- name: set hugepages size
  become: yes
  command: sh -c "echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"

- name: mkdir /mnt/huge
  become: yes
  command: mkdir -p /mnt/huge

- name: mount hugetlbfs
  become: yes
  command: mount -t hugetlbfs nodev /mnt/huge

- name: modprobe uio_pci_generic
  become: yes
  command: modprobe uio_pci_generic

- name: modprobe vfio-pci
  become: yes
  command: modprobe vfio-pci

- name: ifconfig eth2 down
  become: yes
  command: ifconfig eth2 down

- name: ifconfig eth3 down
  become: yes
  command: ifconfig eth3 down

- name: ifconfig eth4 down
  become: yes
  command: ifconfig eth4 down

- name: install build-essential
  become: yes
  apt: pkg=build-essential update_cache=no state=present

- name: install linux-headers
  become: yes
  command: sh -c "apt-get install linux-headers-`uname -r`"
  #vars:
  #  uname_r: 3.19.0-25-generic
  #apt: pkg=linux-headers-{{ uname_r }} update_cache=no state=present
