---
- name: install git 
  become: yes
  apt: name=git state=present update_cache=yes

- name: install vim
  become: yes
  apt: name=vim state=present

- name: install curl
  become: yes
  apt: name=curl state=present

- name: install wget
  become: yes
  apt: name=wget state=present

- name: install PyYAML
  become: yes
  apt: name=python-yaml state=present

- name: create install_dir
  file: path={{ install_dir }} state=directory
